name: Lorentz' dev blog
description: random musings on development, infosec and other stuff that interests me
permalink: pretty
#baseurl: lorentzvedeler.com

collections:
  category:
    output: true

# defaults:
#   -
#     scope:
#       path: ""
#       type: category
#     values:
#       layout: "category"